### ISSUE TITLE
Photomap location pages don't have a map

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2011#37]
Several people have asked that individual photo pages have a map added - as otherwise they don't know where the picture was taken. This is mainly because of people following the Message Of The Day see the picture directly.

Perhaps use a static maps API of some kind just to get a map PNG?

**Comment by si-the-pie** [comment]
Yes, I've missed the maps too.

There are these static maps already in the system, they are fixed size of 256x256 and they could provide a quick solution:

http://cambridge.cyclestreets.net/location/34751/photomaplet34751.png

http://cambridge.cyclestreets.net/location/34751/photomaplet34751zoom18.png

Zoom can be 1 to 18. If unspecified it takes the zoom level that the map was at when the location was set.

This one is experimental, it stitches two zoom levels together so that when a mouse hovers the zoomed in map shows:
http://cambridge.cyclestreets.net/location/34763/photomapletSprite34763.png

**Comment by si-the-pie** [comment]
This was fixed by...
https://github.com/cyclestreets/mobileweb/commit/0425e7a31cd1766e66910744c1b1cbfb9be1bd7a
